# Generated by Django 3.0.2 on 2020-02-03 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='mov_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='mov_title',
            new_name='title',
        ),
    ]
